# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModel',
            new_name='UserProfile',
        ),
    ]
