# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_auth', '0002_auto_20161219_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
